sudo: required

language: bash

services:
  - docker

env:
  - VERSION=6.0.0

before_script:
  - env | sort
  - cd "$VERSION"
  - image="exolyte/activiti:$VERSION"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run -d -p 127.0.0.1:80:8080 exolyte/activiti
  - docker ps -a

# vim:set et ts=2 sw=2:
